name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target=${{ matrix.target }}
      - name: Create OS-specific ZIP
        run: zip -j ${{ matrix.target }}-executable.zip target/${{ matrix.target }}/release/*
      - name: Generate OS-specific SHA-256
        run: sha256sum ${{ matrix.target }}-executable.zip > ${{ matrix.target }}-executable.zip.sha256
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-artifact
          path: |
            ${{ matrix.target }}-executable.zip
            ${{ matrix.target }}-executable.zip.sha256